# Generated by Django 4.2.16 on 2026-04-04 04:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmaterial',
            name='description',
        ),
        migrations.RemoveField(
            model_name='groupmaterial',
            name='downloads',
        ),
        migrations.AddField(
            model_name='group',
            name='dissolve_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='group',
            name='dissolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='is_academic',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='group',
            name='purpose',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='group',
            name='theme',
            field=models.CharField(choices=[('mathematics', 'Mathematics'), ('science', 'Science'), ('arts', 'Arts'), ('technology', 'Technology'), ('sports', 'Sports'), ('music', 'Music'), ('business', 'Business'), ('language', 'Language'), ('gaming', 'Gaming'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='group',
            name='theme_icon',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='groupmaterial',
            name='file_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='groupmaterial',
            name='file_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='group',
            name='category',
            field=models.CharField(choices=[('study', 'Study'), ('hobby', 'Hobby'), ('club', 'Club'), ('faculty', 'Faculty'), ('project', 'Project'), ('arcade', 'Arcade'), ('academic', 'Academic')], default='study', max_length=15),
        ),
        migrations.AlterField(
            model_name='groupmaterial',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupmaterial',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='StudyBuddy',
        ),
    ]
