# apps/quiz/models.py
import uuid
from django.db import models
from django.conf import settings


class GeneratedQuiz(models.Model):
    """
    A quiz generated by the AI from a saved material.

    `questions` is a JSON blob with the shape:
      [
        {
          "id":             "q1",
          "type":           "mcq" | "true_false" | "short",
          "question":       "...",
          "options":        ["A", "B", "C", "D"],   # mcq only
          "correct_answer": "B" | True | "free-form text",
          "explanation":    "Why this is correct..."
        },
        ...
      ]
    """

    class Difficulty(models.TextChoices):
        EASY   = "easy",   "Easy"
        MEDIUM = "medium", "Medium"
        HARD   = "hard",   "Hard"
        MIXED  = "mixed",  "Mixed"

    id           = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user         = models.ForeignKey(settings.AUTH_USER_MODEL,
                                     on_delete=models.CASCADE,
                                     related_name="generated_quizzes")

    # Source — usually a SavedMaterial, but we keep title/subject denormalised
    # so the quiz survives even if the user later deletes the material.
    material     = models.ForeignKey("chat.SavedMaterial",
                                     on_delete=models.SET_NULL,
                                     null=True, blank=True,
                                     related_name="quizzes")
    title        = models.CharField(max_length=200)
    subject      = models.CharField(max_length=100, blank=True)

    difficulty   = models.CharField(max_length=10,
                                    choices=Difficulty.choices,
                                    default=Difficulty.MEDIUM)
    num_questions = models.PositiveSmallIntegerField(default=10)
    question_types = models.JSONField(
        default=list,
        help_text="Subset of ['mcq','true_false','short']. Empty = all.")

    questions    = models.JSONField(default=list)

    # Token accounting — useful if we ever charge tokens for generation.
    tokens_used  = models.PositiveIntegerField(default=0)
    model_name   = models.CharField(max_length=60, blank=True)

    created_at   = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "generated_quizzes"
        ordering = ["-created_at"]
        indexes  = [models.Index(fields=["user", "-created_at"])]

    def __str__(self):
        return f"{self.title} ({self.user_id})"


class QuizAttempt(models.Model):
    """One attempt at a generated quiz. A user can take a quiz multiple times."""

    id          = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    quiz        = models.ForeignKey(GeneratedQuiz, on_delete=models.CASCADE,
                                    related_name="attempts")
    user        = models.ForeignKey(settings.AUTH_USER_MODEL,
                                    on_delete=models.CASCADE,
                                    related_name="quiz_attempts")

    # Frontend posts: { "q1": "B", "q2": True, "q3": "Newton's third law" }
    answers     = models.JSONField(default=dict)

    score       = models.PositiveSmallIntegerField(default=0)   # correct count
    total       = models.PositiveSmallIntegerField(default=0)   # questions answered
    percentage  = models.FloatField(default=0.0)

    duration_seconds = models.PositiveIntegerField(default=0)
    completed_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "quiz_attempts"
        ordering = ["-completed_at"]
        indexes  = [models.Index(fields=["quiz", "-completed_at"])]

    def __str__(self):
        return f"{self.user_id} → {self.quiz_id}: {self.score}/{self.total}"