# Generated by Django 4.2.16 on 2026-04-04 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('puzzle', 'Puzzle'), ('action', 'Action'), ('trivia', 'Trivia'), ('multiplayer', 'Multiplayer'), ('coop', 'Co-op'), ('racing', 'Racing'), ('strategy', 'Strategy'), ('sports', 'Sports')], max_length=15)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='game_thumbs/')),
                ('min_players', models.PositiveSmallIntegerField(default=1)),
                ('max_players', models.PositiveSmallIntegerField(default=8)),
                ('xp_reward', models.PositiveSmallIntegerField(default=50)),
                ('token_reward', models.PositiveSmallIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('play_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'games',
            },
        ),
        migrations.CreateModel(
            name='GameRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('game_slug', models.CharField(max_length=60)),
                ('game_name', models.CharField(max_length=100)),
                ('wager', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_challenges', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'game_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens', models.IntegerField(default=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'player_stats',
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('game_slug', models.CharField(max_length=60)),
                ('wager', models.IntegerField(default=0)),
                ('p1_score', models.IntegerField(default=0)),
                ('p2_score', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('p1_paused', models.BooleanField(default=False)),
                ('p2_paused', models.BooleanField(default=False)),
                ('p1_quit', models.BooleanField(default=False)),
                ('p2_quit', models.BooleanField(default=False)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p1_sessions', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2_sessions', to=settings.AUTH_USER_MODEL)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='arcade.gamerequest')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'game_sessions',
            },
        ),
        migrations.CreateModel(
            name='GameScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='arcade.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'game_scores',
                'ordering': ['-score'],
                'indexes': [models.Index(fields=['game', '-score'], name='game_scores_game_id_c728c7_idx')],
            },
        ),
    ]
