# Generated by Django 4.2.16 on 2026-05-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0002_aracade_overhaul'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamesession',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameIndex(
            model_name='gameinvite',
            new_name='game_invite_sender__21b61e_idx',
            old_name='game_invite_sender_status_idx',
        ),
        migrations.RenameIndex(
            model_name='gameinvite',
            new_name='game_invite_status_8b04f3_idx',
            old_name='game_invite_status_exp_idx',
        ),
        migrations.RenameIndex(
            model_name='gamesession',
            new_name='game_sessio_status_1a5808_idx',
            old_name='game_session_status_idx',
        ),
        migrations.RenameIndex(
            model_name='gamesession',
            new_name='game_sessio_game_sl_06d9b3_idx',
            old_name='game_session_slug_idx',
        ),
        migrations.RenameIndex(
            model_name='matchmessage',
            new_name='match_messa_session_a1c9c7_idx',
            old_name='match_msg_session_idx',
        ),
        migrations.RenameIndex(
            model_name='tokenledger',
            new_name='token_ledge_user_id_8eede7_idx',
            old_name='ledger_user_time_idx',
        ),
        migrations.RenameIndex(
            model_name='tokenledger',
            new_name='token_ledge_referen_3f9b34_idx',
            old_name='ledger_ref_idx',
        ),
        migrations.RenameIndex(
            model_name='tokentransfer',
            new_name='token_trans_sender__bfa851_idx',
            old_name='transfer_sender_idx',
        ),
        migrations.RenameIndex(
            model_name='tokentransfer',
            new_name='token_trans_recipie_4046ee_idx',
            old_name='transfer_recipient_idx',
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='game_slug',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='matchmessage',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sessionplayer',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tokenledger',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
