# Generated by Django 4.2.16 on 2026-05-02 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('feature', '💡 Feature Request'), ('bug', '🐛 Bug Report'), ('content', '📚 Content & Curriculum'), ('ui', '🎨 Design & UI'), ('complaint', '⚠️ Complaint')], max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('under_review', 'Under Review'), ('planned', 'Planned'), ('done', 'Done'), ('wont_do', "Won't Do")], default='new', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'suggestions',
                'ordering': ['-created_at'],
            },
        ),
    ]
