# Generated by Django 4.2.16 on 2026-05-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_categories_overhaul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='gradient_from',
            field=models.CharField(default='#6DD5FA', help_text='Hex starting colour for the picker tile gradient.', max_length=9),
        ),
        migrations.AlterField(
            model_name='category',
            name='gradient_to',
            field=models.CharField(default='#8E54E9', help_text='Hex ending colour for the picker tile gradient.', max_length=9),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Inactive categories stay in the DB but don't appear in the picker API."),
        ),
        migrations.AlterField(
            model_name='category',
            name='key',
            field=models.SlugField(help_text="Stable identifier sent over the wire (e.g. 'bug').", max_length=40, unique=True),
        ),
    ]
