# Generated by Django 4.2.16 on 2026-05-15 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0003_add_praise_category"),
        ("feedback", "0003_alter_category_gradient_from_and_more"),
    ]

    operations = []
