# Generated by Django 4.2.16 on 2026-05-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("highlights", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="highlightitem",
            name="caption",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
