# Generated by Django 4.2.16 on 2026-05-09 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='generatedquiz',
            new_name='generated_q_user_id_7791e0_idx',
            old_name='gen_quiz_user_dt_idx',
        ),
        migrations.RenameIndex(
            model_name='quizattempt',
            new_name='quiz_attemp_quiz_id_3bcaa1_idx',
            old_name='quiz_att_quiz_dt_idx',
        ),
    ]
