# Generated by Django 5.2.8 on 2026-05-24 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0003_clubinvite"),
        ("events", "0002_event_club"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="club",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="clubs.club",
            ),
        ),
    ]
