// lib/screens/arcade/levels/battle_bots_levels.dart

import 'package:flutter/material.dart';
import '../game_engine.dart';
import '../level_system.dart';

const kBattleBotsLevels = <LevelConfig>[
  LevelConfig(level: 1,
    title: 'Circuit Beginner', subtitle: '5×5 grid, weak enemies',
    targetScore: 300, icon: Icons.smart_toy_rounded,
    gradient: [kNeonBlue, kNeonPurple],
    params: {'grid': 5, 'enemyBots': 2, 'enemyHp': 3, 'enemyAtk': 1}),
  LevelConfig(level: 2,
    title: 'Test Lab', subtitle: 'Bigger arena',
    targetScore: 450, icon: Icons.science_rounded,
    gradient: [kNeonBlue, kNeonPurple],
    params: {'grid': 6, 'enemyBots': 2, 'enemyHp': 4, 'enemyAtk': 1}),
  LevelConfig(level: 3,
    title: 'Steel Arena', subtitle: 'Three enemies now',
    targetScore: 600, icon: Icons.shield_rounded,
    gradient: [Color(0xFF485563), Color(0xFF29323C)],
    params: {'grid': 6, 'enemyBots': 3, 'enemyHp': 4, 'enemyAtk': 2}),
  LevelConfig(level: 4,
    title: 'Plasma Pit', subtitle: 'Stronger attacks',
    targetScore: 800, icon: Icons.flash_on_rounded,
    gradient: [Color(0xFF485563), Color(0xFF29323C)],
    params: {'grid': 7, 'enemyBots': 3, 'enemyHp': 5, 'enemyAtk': 2}),
  LevelConfig(level: 5,
    title: 'Rust Belt', subtitle: 'Halfway through the campaign',
    targetScore: 1050, icon: Icons.handyman_rounded,
    gradient: [Color(0xFFFF512F), Color(0xFFDD2476)],
    params: {'grid': 7, 'enemyBots': 4, 'enemyHp': 5, 'enemyAtk': 2}),
  LevelConfig(level: 6,
    title: 'Iron Foundry', subtitle: 'Tougher patrols',
    targetScore: 1350, icon: Icons.warehouse_rounded,
    gradient: [Color(0xFFFF512F), Color(0xFFDD2476)],
    params: {'grid': 7, 'enemyBots': 4, 'enemyHp': 6, 'enemyAtk': 3}),
  LevelConfig(level: 7,
    title: 'Omega Protocol', subtitle: 'Fully armed enemies',
    targetScore: 1700, icon: Icons.security_rounded,
    gradient: [Color(0xFF8E2DE2), Color(0xFF4A00E0)],
    params: {'grid': 8, 'enemyBots': 5, 'enemyHp': 6, 'enemyAtk': 3}),
  LevelConfig(level: 8,
    title: 'AI Citadel', subtitle: 'Heavy resistance',
    targetScore: 2100, icon: Icons.memory_rounded,
    gradient: [Color(0xFF8E2DE2), Color(0xFF4A00E0)],
    params: {'grid': 8, 'enemyBots': 5, 'enemyHp': 7, 'enemyAtk': 3}),
  LevelConfig(level: 9,
    title: 'Robot Rebellion', subtitle: 'Last stand',
    targetScore: 2600, icon: Icons.local_fire_department_rounded,
    gradient: [kNeonRed, Color(0xFF870000)],
    params: {'grid': 8, 'enemyBots': 6, 'enemyHp': 8, 'enemyAtk': 4}),
  LevelConfig(level: 10,
    title: 'Engineering Cup', subtitle: 'Crown the champion',
    targetScore: 3200, icon: Icons.emoji_events_rounded,
    gradient: [Color(0xFFFFD700), Color(0xFFFFA000)],
    params: {'grid': 9, 'enemyBots': 7, 'enemyHp': 8, 'enemyAtk': 4}),
];
