// lib/screens/arcade/levels/memory_match_levels.dart

import 'package:flutter/material.dart';
import '../game_engine.dart';
import '../level_system.dart';

const kMemoryMatchLevels = <LevelConfig>[
  LevelConfig(level: 1,
    title: 'Quick Memory',  subtitle: '8 cards · 4 pairs',
    targetScore: 600, icon: Icons.psychology_rounded,
    gradient: [kNeonBlue, kNeonPurple],
    params: {'cols': 4, 'rows': 2, 'flipBack': 1000}),
  LevelConfig(level: 2,
    title: 'Card Practice', subtitle: '12 cards · 6 pairs',
    targetScore: 800, icon: Icons.style_rounded,
    gradient: [kNeonBlue, kNeonPurple],
    params: {'cols': 4, 'rows': 3, 'flipBack': 1000}),
  LevelConfig(level: 3,
    title: 'Pattern Match', subtitle: '16 cards · 8 pairs',
    targetScore: 1100, icon: Icons.grid_view_rounded,
    gradient: [Color(0xFFFC466B), Color(0xFF3F5EFB)],
    params: {'cols': 4, 'rows': 4, 'flipBack': 900}),
  LevelConfig(level: 4,
    title: 'Sharp Mind',    subtitle: '20 cards · faster flip',
    targetScore: 1500, icon: Icons.flash_on_rounded,
    gradient: [Color(0xFFFC466B), Color(0xFF3F5EFB)],
    params: {'cols': 5, 'rows': 4, 'flipBack': 800}),
  LevelConfig(level: 5,
    title: 'Lab Test',      subtitle: '24 cards · halfway!',
    targetScore: 1900, icon: Icons.science_rounded,
    gradient: [kNeonPurple, Color(0xFF4A00E0)],
    params: {'cols': 6, 'rows': 4, 'flipBack': 800}),
  LevelConfig(level: 6,
    title: 'Photographic',  subtitle: '28 cards',
    targetScore: 2400, icon: Icons.camera_alt_rounded,
    gradient: [kNeonPurple, Color(0xFF4A00E0)],
    params: {'cols': 7, 'rows': 4, 'flipBack': 700}),
  LevelConfig(level: 7,
    title: 'Eidetic',       subtitle: '30 cards · fast peek',
    targetScore: 2900, icon: Icons.visibility_rounded,
    gradient: [kNeonOrange, kNeonRed],
    params: {'cols': 6, 'rows': 5, 'flipBack': 600}),
  LevelConfig(level: 8,
    title: 'Speed Demon',   subtitle: '36 cards',
    targetScore: 3500, icon: Icons.bolt_rounded,
    gradient: [kNeonOrange, kNeonRed],
    params: {'cols': 6, 'rows': 6, 'flipBack': 600}),
  LevelConfig(level: 9,
    title: 'Master Memory', subtitle: '42 cards · blink fast',
    targetScore: 4200, icon: Icons.workspace_premium_rounded,
    gradient: [Color(0xFFFFD700), Color(0xFFF7971E)],
    params: {'cols': 7, 'rows': 6, 'flipBack': 500}),
  LevelConfig(level: 10,
    title: 'Memory Champion', subtitle: '48 cards · legendary',
    targetScore: 5200, icon: Icons.emoji_events_rounded,
    gradient: [Color(0xFFFFD700), Color(0xFFFFA000)],
    params: {'cols': 8, 'rows': 6, 'flipBack': 500}),
];
