// lib/screens/arcade/levels/ninja_tag_levels.dart

import 'package:flutter/material.dart';
import '../game_engine.dart';
import '../level_system.dart';

const kNinjaTagLevels = <LevelConfig>[
  LevelConfig(level: 1,
    title: 'Training Dojo', subtitle: '6×6 grid, 1 enemy',
    targetScore: 80, icon: Icons.school_rounded,
    gradient: [kNeonRed, kNeonPurple],
    params: {'grid': 6,  'enemies': 1, 'speed': 700, 'stars':  6, 'time': 60}),
  LevelConfig(level: 2,
    title: 'Garden Path', subtitle: 'A second shadow joins',
    targetScore: 110, icon: Icons.park_rounded,
    gradient: [kNeonRed, kNeonPurple],
    params: {'grid': 6,  'enemies': 2, 'speed': 600, 'stars':  7, 'time': 60}),
  LevelConfig(level: 3,
    title: 'Shadow Village', subtitle: '7×7 with more stars',
    targetScore: 150, icon: Icons.location_city_rounded,
    gradient: [Color(0xFF8E2DE2), Color(0xFF4A00E0)],
    params: {'grid': 7,  'enemies': 2, 'speed': 550, 'stars':  9, 'time': 70}),
  LevelConfig(level: 4,
    title: 'Bamboo Forest', subtitle: 'Walls everywhere',
    targetScore: 200, icon: Icons.forest_rounded,
    gradient: [Color(0xFF8E2DE2), Color(0xFF4A00E0)],
    params: {'grid': 7,  'enemies': 3, 'speed': 480, 'stars': 10, 'time': 75}),
  LevelConfig(level: 5,
    title: 'Mountain Path', subtitle: 'Halfway through',
    targetScore: 260, icon: Icons.terrain_rounded,
    gradient: [Color(0xFF134E5E), Color(0xFF71B280)],
    params: {'grid': 8,  'enemies': 3, 'speed': 420, 'stars': 12, 'time': 80}),
  LevelConfig(level: 6,
    title: 'Twilight Market', subtitle: 'Phantoms move faster',
    targetScore: 330, icon: Icons.dark_mode_rounded,
    gradient: [Color(0xFF134E5E), Color(0xFF71B280)],
    params: {'grid': 8,  'enemies': 3, 'speed': 360, 'stars': 14, 'time': 80}),
  LevelConfig(level: 7,
    title: 'Castle Walls', subtitle: 'A bigger maze',
    targetScore: 410, icon: Icons.castle_rounded,
    gradient: [Color(0xFF614385), Color(0xFF516395)],
    params: {'grid': 9,  'enemies': 4, 'speed': 320, 'stars': 16, 'time': 85}),
  LevelConfig(level: 8,
    title: 'Storm Temple', subtitle: 'Stars hidden deeper',
    targetScore: 510, icon: Icons.thunderstorm_rounded,
    gradient: [Color(0xFF614385), Color(0xFF516395)],
    params: {'grid': 9,  'enemies': 4, 'speed': 280, 'stars': 18, 'time': 85}),
  LevelConfig(level: 9,
    title: 'Final Showdown', subtitle: 'Five phantoms hunt you',
    targetScore: 620, icon: Icons.warning_rounded,
    gradient: [kNeonRed, Color(0xFF870000)],
    params: {'grid': 10, 'enemies': 5, 'speed': 250, 'stars': 20, 'time': 90}),
  LevelConfig(level: 10,
    title: 'Master Ninja', subtitle: 'Ultimate test',
    targetScore: 800, icon: Icons.emoji_events_rounded,
    gradient: [Color(0xFFFFD700), Color(0xFFFFA000)],
    params: {'grid': 10, 'enemies': 6, 'speed': 220, 'stars': 22, 'time': 90}),
];
