// lib/screens/arcade/levels/spirit_racers_levels.dart
//
// 10-level progression for Spirit Racers.
// Speed, spawn rate, and obstacle width all scale.

import 'package:flutter/material.dart';
import '../game_engine.dart';
import '../level_system.dart';

const kSpiritRacersLevels = <LevelConfig>[
  LevelConfig(level: 1,
    title: 'Rookie Track', subtitle: 'Get a feel for the wheels',
    targetScore: 800, icon: Icons.directions_car_rounded,
    gradient: [kNeonBlue, kNeonOrange],
    params: {'speed': 4.0, 'spawnRate': 90, 'lanes': 3}),
  LevelConfig(level: 2,
    title: 'Suburban Sprint', subtitle: 'A little more traffic',
    targetScore: 1200, icon: Icons.directions_car_rounded,
    gradient: [kNeonBlue, kNeonOrange],
    params: {'speed': 5.0, 'spawnRate': 75, 'lanes': 3}),
  LevelConfig(level: 3,
    title: 'Highway Cruise', subtitle: 'Picking up speed',
    targetScore: 1700, icon: Icons.fast_forward_rounded,
    gradient: [Color(0xFF11998E), Color(0xFF38EF7D)],
    params: {'speed': 6.0, 'spawnRate': 65, 'lanes': 3}),
  LevelConfig(level: 4,
    title: 'Coastal Curves', subtitle: '4 lanes, harder dodges',
    targetScore: 2300, icon: Icons.timeline_rounded,
    gradient: [Color(0xFF11998E), Color(0xFF38EF7D)],
    params: {'speed': 6.5, 'spawnRate': 60, 'lanes': 4}),
  LevelConfig(level: 5,
    title: 'City Lights', subtitle: 'Halfway home',
    targetScore: 3000, icon: Icons.location_city_rounded,
    gradient: [kNeonPurple, Color(0xFF6B2FD9)],
    params: {'speed': 7.0, 'spawnRate': 55, 'lanes': 4}),
  LevelConfig(level: 6,
    title: 'Storm Chase', subtitle: 'Reaction time matters',
    targetScore: 3700, icon: Icons.bolt_rounded,
    gradient: [kNeonPurple, Color(0xFF6B2FD9)],
    params: {'speed': 7.5, 'spawnRate': 48, 'lanes': 4}),
  LevelConfig(level: 7,
    title: 'Night Run', subtitle: 'The track gets serious',
    targetScore: 4500, icon: Icons.dark_mode_rounded,
    gradient: [Color(0xFF232526), Color(0xFF414345)],
    params: {'speed': 8.0, 'spawnRate': 45, 'lanes': 4}),
  LevelConfig(level: 8,
    title: 'Turbo Boost', subtitle: 'Almost too fast to react',
    targetScore: 5500, icon: Icons.local_fire_department_rounded,
    gradient: [kNeonOrange, kNeonRed],
    params: {'speed': 8.5, 'spawnRate': 40, 'lanes': 4}),
  LevelConfig(level: 9,
    title: 'Spirit Cup Semi', subtitle: 'Pro circuit speed',
    targetScore: 6500, icon: Icons.sports_score_rounded,
    gradient: [kNeonOrange, kNeonRed],
    params: {'speed': 9.0, 'spawnRate': 35, 'lanes': 4}),
  LevelConfig(level: 10,
    title: 'Spirit Cup Final', subtitle: 'Champion run — full chaos',
    targetScore: 8000, icon: Icons.emoji_events_rounded,
    gradient: [Color(0xFFFFD700), Color(0xFFFFA000)],
    params: {'speed': 10.0, 'spawnRate': 30, 'lanes': 4}),
];
