// lib/screens/arcade/levels/sushi_rush_levels.dart

import 'package:flutter/material.dart';
import '../game_engine.dart';
import '../level_system.dart';

const kSushiRushLevels = <LevelConfig>[
  LevelConfig(level: 1,
    title: 'Apprentice', subtitle: 'Short orders, plenty of time',
    targetScore: 400, icon: Icons.ramen_dining_rounded,
    gradient: [kNeonOrange, kNeonRed],
    params: {'orderLen': 3, 'rounds': 4, 'showTime': 2500, 'inputTime': 9000}),
  LevelConfig(level: 2,
    title: 'Line Cook', subtitle: 'A bit faster now',
    targetScore: 600, icon: Icons.ramen_dining_rounded,
    gradient: [kNeonOrange, kNeonRed],
    params: {'orderLen': 4, 'rounds': 5, 'showTime': 2200, 'inputTime': 8500}),
  LevelConfig(level: 3,
    title: 'Lunch Rush', subtitle: 'Customers piling up',
    targetScore: 850, icon: Icons.fastfood_rounded,
    gradient: [Color(0xFFFF512F), Color(0xFFF09819)],
    params: {'orderLen': 5, 'rounds': 6, 'showTime': 2000, 'inputTime': 8000}),
  LevelConfig(level: 4,
    title: 'Dinner Service', subtitle: 'No mistakes allowed',
    targetScore: 1100, icon: Icons.restaurant_rounded,
    gradient: [Color(0xFFFF512F), Color(0xFFF09819)],
    params: {'orderLen': 5, 'rounds': 7, 'showTime': 1700, 'inputTime': 7500}),
  LevelConfig(level: 5,
    title: 'Head Chef', subtitle: 'Halfway to legend',
    targetScore: 1400, icon: Icons.local_fire_department_rounded,
    gradient: [Color(0xFFB24592), Color(0xFFF15F79)],
    params: {'orderLen': 6, 'rounds': 8, 'showTime': 1500, 'inputTime': 7000}),
  LevelConfig(level: 6,
    title: 'Friday Night', subtitle: 'Memory speed test',
    targetScore: 1750, icon: Icons.nightlife_rounded,
    gradient: [Color(0xFFB24592), Color(0xFFF15F79)],
    params: {'orderLen': 6, 'rounds': 9, 'showTime': 1300, 'inputTime': 6500}),
  LevelConfig(level: 7,
    title: 'Critic in House', subtitle: 'Speed and accuracy',
    targetScore: 2150, icon: Icons.rate_review_rounded,
    gradient: [kNeonPurple, Color(0xFF6B2FD9)],
    params: {'orderLen': 7, 'rounds': 9, 'showTime': 1200, 'inputTime': 6000}),
  LevelConfig(level: 8,
    title: 'Banquet Hall', subtitle: 'Long orders, tight clock',
    targetScore: 2600, icon: Icons.celebration_rounded,
    gradient: [kNeonPurple, Color(0xFF6B2FD9)],
    params: {'orderLen': 8, 'rounds': 10, 'showTime': 1100, 'inputTime': 5500}),
  LevelConfig(level: 9,
    title: 'Iron Chef', subtitle: 'Master-level pace',
    targetScore: 3100, icon: Icons.workspace_premium_rounded,
    gradient: [kNeonOrange, Color(0xFFFFD700)],
    params: {'orderLen': 9, 'rounds': 10, 'showTime': 1000, 'inputTime': 5000}),
  LevelConfig(level: 10,
    title: 'Sushi Sensei', subtitle: 'Legendary status',
    targetScore: 3800, icon: Icons.emoji_events_rounded,
    gradient: [Color(0xFFFFD700), Color(0xFFFFA000)],
    params: {'orderLen': 10, 'rounds': 12, 'showTime': 900, 'inputTime': 4500}),
];
