# Generated by Django 4.2.16 on 2026-05-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="chat_room_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
