# Generated by Django 4.2.16 on 2026-05-19 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, unique=True)),
                ('severity', models.CharField(choices=[('warn', 'Warn (allow but flag)'), ('reject', 'Reject submission')], default='reject', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'moderation_blocked_keywords',
                'ordering': ['keyword'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.CharField(max_length=64)),
                ('reason', models.CharField(choices=[('spam', 'Spam or misleading'), ('harassment', 'Harassment or bullying'), ('hate_speech', 'Hate speech or symbols'), ('violence', 'Violence or dangerous content'), ('sexual', 'Sexual or adult content'), ('self_harm', 'Self-harm or suicide'), ('illegal', 'Illegal activity'), ('false_info', 'False information'), ('other', 'Other')], max_length=32)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed (no action)'), ('actioned', 'Content removed / user banned'), ('dismissed', 'Dismissed')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'moderation_reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='moderation__content_42c715_idx'), models.Index(fields=['status', '-created_at'], name='moderation__status_18f3f1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(blank=True, choices=[('spam', 'Spam or misleading'), ('harassment', 'Harassment or bullying'), ('hate_speech', 'Hate speech or symbols'), ('violence', 'Violence or dangerous content'), ('sexual', 'Sexual or adult content'), ('self_harm', 'Self-harm or suicide'), ('illegal', 'Illegal activity'), ('false_info', 'False information'), ('other', 'Other')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'moderation_blocks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['blocker', 'blocked'], name='moderation__blocker_77c60c_idx')],
                'unique_together': {('blocker', 'blocked')},
            },
        ),
    ]
