# Generated by Django 4.2.16 on 2026-03-28 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_type', models.CharField(choices=[('teaching', 'Teaching'), ('security', 'Security'), ('cleaning', 'Cleaning'), ('administrative', 'Administrative'), ('reception', 'Reception')], max_length=20)),
                ('staff_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('preferred_name', models.CharField(blank=True, max_length=80)),
                ('date_of_birth', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'staff_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('preferred_name', models.CharField(blank=True, max_length=80)),
                ('student_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('date_of_birth', models.DateField()),
                ('course_type', models.CharField(choices=[('standard', 'Standard Programme'), ('intensive', 'Intensive Programme')], max_length=20)),
                ('date_of_commencement', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'student_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
