// lib/screens/arcade/levels/number_guesser_levels.dart

import 'package:flutter/material.dart';
import '../game_engine.dart';
import '../level_system.dart';

const kNumberGuesserLevels = <LevelConfig>[
  LevelConfig(level: 1,
    title: 'Simple Code', subtitle: '1-50 · 8 guesses',
    targetScore: 250, icon: Icons.numbers_rounded,
    gradient: [kNeonOrange, kNeonRed],
    params: {'min': 1, 'max':   50, 'guesses':  8}),
  LevelConfig(level: 2,
    title: 'Hex Lock',    subtitle: '1-100 · 8 guesses',
    targetScore: 350, icon: Icons.lock_rounded,
    gradient: [kNeonOrange, kNeonRed],
    params: {'min': 1, 'max':  100, 'guesses':  8}),
  LevelConfig(level: 3,
    title: 'Vault Code',  subtitle: '1-200 · 9 guesses',
    targetScore: 500, icon: Icons.vpn_lock_rounded,
    gradient: [Color(0xFFFC466B), Color(0xFF3F5EFB)],
    params: {'min': 1, 'max':  200, 'guesses':  9}),
  LevelConfig(level: 4,
    title: 'Lab Vault',   subtitle: '1-300 · 9 guesses',
    targetScore: 650, icon: Icons.security_rounded,
    gradient: [Color(0xFFFC466B), Color(0xFF3F5EFB)],
    params: {'min': 1, 'max':  300, 'guesses':  9}),
  LevelConfig(level: 5,
    title: 'Cipher',      subtitle: '1-500 · 10 guesses',
    targetScore: 850, icon: Icons.key_rounded,
    gradient: [kNeonPurple, Color(0xFF4A00E0)],
    params: {'min': 1, 'max':  500, 'guesses': 10}),
  LevelConfig(level: 6,
    title: 'Quantum Lock',subtitle: '1-750 · 10 guesses',
    targetScore: 1100, icon: Icons.scatter_plot_rounded,
    gradient: [kNeonPurple, Color(0xFF4A00E0)],
    params: {'min': 1, 'max':  750, 'guesses': 10}),
  LevelConfig(level: 7,
    title: 'Encryption',  subtitle: '1-1000 · 11 guesses',
    targetScore: 1400, icon: Icons.shield_rounded,
    gradient: [Color(0xFF8E2DE2), Color(0xFF4A00E0)],
    params: {'min': 1, 'max': 1000, 'guesses': 11}),
  LevelConfig(level: 8,
    title: 'Master Key',  subtitle: '1-2000 · 12 guesses',
    targetScore: 1750, icon: Icons.vpn_key_rounded,
    gradient: [Color(0xFF8E2DE2), Color(0xFF4A00E0)],
    params: {'min': 1, 'max': 2000, 'guesses': 12}),
  LevelConfig(level: 9,
    title: 'Mainframe',   subtitle: '1-5000 · 13 guesses',
    targetScore: 2200, icon: Icons.dns_rounded,
    gradient: [kNeonOrange, kNeonRed],
    params: {'min': 1, 'max': 5000, 'guesses': 13}),
  LevelConfig(level: 10,
    title: 'Code Breaker',subtitle: '1-10000 · 14 guesses',
    targetScore: 2800, icon: Icons.emoji_events_rounded,
    gradient: [Color(0xFFFFD700), Color(0xFFFFA000)],
    params: {'min': 1, 'max':10000, 'guesses': 14}),
];
