// lib/screens/arcade/levels/pool_royale_levels.dart

import 'package:flutter/material.dart';
import '../game_engine.dart';
import '../level_system.dart';

const kPoolRoyaleLevels = <LevelConfig>[
  LevelConfig(level: 1,
    title: 'Beginner Table', subtitle: '4 balls, easy pockets',
    targetScore: 250, icon: Icons.sports_rounded,
    gradient: [Color(0xFF11998E), Color(0xFF38EF7D)],
    params: {'balls':  4, 'pocketBonus':  60, 'maxShots': 30}),
  LevelConfig(level: 2,
    title: 'Practice Hall', subtitle: 'Five-ball sweep',
    targetScore: 400, icon: Icons.sports_rounded,
    gradient: [Color(0xFF11998E), Color(0xFF38EF7D)],
    params: {'balls':  5, 'pocketBonus':  70, 'maxShots': 28}),
  LevelConfig(level: 3,
    title: 'Local Cup', subtitle: 'Six balls now',
    targetScore: 550, icon: Icons.local_bar_rounded,
    gradient: [kNeonBlue, kNeonPurple],
    params: {'balls':  6, 'pocketBonus':  80, 'maxShots': 26}),
  LevelConfig(level: 4,
    title: 'Amateur Cup', subtitle: 'Tighter pockets',
    targetScore: 750, icon: Icons.workspace_premium_rounded,
    gradient: [kNeonBlue, kNeonPurple],
    params: {'balls':  7, 'pocketBonus':  90, 'maxShots': 24}),
  LevelConfig(level: 5,
    title: 'Pub Champion', subtitle: 'Halfway to pro',
    targetScore: 950, icon: Icons.sports_bar_rounded,
    gradient: [kNeonPurple, Color(0xFF4A00E0)],
    params: {'balls':  8, 'pocketBonus': 100, 'maxShots': 22}),
  LevelConfig(level: 6,
    title: 'City Open', subtitle: 'Eight-ball challenge',
    targetScore: 1200, icon: Icons.location_city_rounded,
    gradient: [kNeonPurple, Color(0xFF4A00E0)],
    params: {'balls':  9, 'pocketBonus': 110, 'maxShots': 20}),
  LevelConfig(level: 7,
    title: 'Pro Circuit', subtitle: 'Skill required',
    targetScore: 1500, icon: Icons.star_rounded,
    gradient: [kNeonOrange, kNeonRed],
    params: {'balls':  9, 'pocketBonus': 120, 'maxShots': 18}),
  LevelConfig(level: 8,
    title: 'Masters Tour', subtitle: 'Precision matters',
    targetScore: 1850, icon: Icons.workspace_premium_rounded,
    gradient: [kNeonOrange, kNeonRed],
    params: {'balls': 10, 'pocketBonus': 130, 'maxShots': 17}),
  LevelConfig(level: 9,
    title: 'World Series', subtitle: 'Top 4 players',
    targetScore: 2200, icon: Icons.public_rounded,
    gradient: [Color(0xFFFFD700), Color(0xFFF7971E)],
    params: {'balls': 10, 'pocketBonus': 140, 'maxShots': 16}),
  LevelConfig(level: 10,
    title: 'Midnight Final', subtitle: 'Cue master title',
    targetScore: 2700, icon: Icons.emoji_events_rounded,
    gradient: [Color(0xFFFFD700), Color(0xFFFFA000)],
    params: {'balls': 11, 'pocketBonus': 150, 'maxShots': 15}),
];
