// lib/screens/arcade/levels/snake_levels.dart

import 'package:flutter/material.dart';
import '../game_engine.dart';
import '../level_system.dart';

const kSnakeLevels = <LevelConfig>[
  LevelConfig(level: 1,
    title: 'Server Room', subtitle: 'Find the data nodes',
    targetScore: 80, icon: Icons.storage_rounded,
    gradient: [Color(0xFF11998E), Color(0xFF38EF7D)],
    params: {'gridSize': 14, 'speedMs': 220, 'walls': 0,  'food': 1}),
  LevelConfig(level: 2,
    title: 'Cooling Bay', subtitle: 'A bit longer, a bit faster',
    targetScore: 130, icon: Icons.ac_unit_rounded,
    gradient: [Color(0xFF11998E), Color(0xFF38EF7D)],
    params: {'gridSize': 14, 'speedMs': 200, 'walls': 0,  'food': 1}),
  LevelConfig(level: 3,
    title: 'Cable Maze', subtitle: 'Walls appear',
    targetScore: 200, icon: Icons.cable_rounded,
    gradient: [kNeonBlue, kNeonPurple],
    params: {'gridSize': 14, 'speedMs': 180, 'walls': 4,  'food': 1}),
  LevelConfig(level: 4,
    title: 'Power Grid', subtitle: 'More walls, more food',
    targetScore: 280, icon: Icons.electrical_services_rounded,
    gradient: [kNeonBlue, kNeonPurple],
    params: {'gridSize': 14, 'speedMs': 160, 'walls': 6,  'food': 2}),
  LevelConfig(level: 5,
    title: 'Memory Banks', subtitle: 'Halfway through',
    targetScore: 380, icon: Icons.memory_rounded,
    gradient: [kNeonPurple, Color(0xFF4A00E0)],
    params: {'gridSize': 16, 'speedMs': 150, 'walls': 8,  'food': 2}),
  LevelConfig(level: 6,
    title: 'CPU Core', subtitle: 'Speed picks up',
    targetScore: 500, icon: Icons.computer_rounded,
    gradient: [kNeonPurple, Color(0xFF4A00E0)],
    params: {'gridSize': 16, 'speedMs': 130, 'walls': 10, 'food': 2}),
  LevelConfig(level: 7,
    title: 'Quantum Layer', subtitle: 'Walls everywhere',
    targetScore: 650, icon: Icons.scatter_plot_rounded,
    gradient: [kNeonOrange, kNeonRed],
    params: {'gridSize': 18, 'speedMs': 115, 'walls': 14, 'food': 3}),
  LevelConfig(level: 8,
    title: 'Firewall', subtitle: 'Reaction speed test',
    targetScore: 820, icon: Icons.local_fire_department_rounded,
    gradient: [kNeonOrange, kNeonRed],
    params: {'gridSize': 18, 'speedMs': 100, 'walls': 18, 'food': 3}),
  LevelConfig(level: 9,
    title: 'Mainframe', subtitle: 'Almost too fast',
    targetScore: 1000, icon: Icons.dns_rounded,
    gradient: [Color(0xFFFC466B), Color(0xFF3F5EFB)],
    params: {'gridSize': 20, 'speedMs':  90, 'walls': 22, 'food': 3}),
  LevelConfig(level: 10,
    title: 'Server Sentinel', subtitle: 'Max chaos — be the legend',
    targetScore: 1300, icon: Icons.emoji_events_rounded,
    gradient: [Color(0xFFFFD700), Color(0xFFFFA000)],
    params: {'gridSize': 20, 'speedMs':  80, 'walls': 26, 'food': 4}),
];
