# Generated by Django 4.2.16 on 2026-05-09 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], db_index=True, default='pending', max_length=10)),
                ('message', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chat_room_invites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='message',
            name='is_ai',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='room',
            name='ai_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='is_public',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='savedmaterial',
            name='source_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_materials', to='groups.group'),
        ),
        migrations.AddField(
            model_name='savedmaterial',
            name='source_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='savedmaterial',
            name='source_type',
            field=models.CharField(blank=True, choices=[('chat', 'Chat'), ('group', 'Study Group'), ('manual', 'Manual upload')], default='chat', max_length=20),
        ),
        migrations.AddField(
            model_name='savedmaterial',
            name='subject',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='savedmaterial',
            index=models.Index(fields=['user', 'subject'], name='savedmat_user_subj_idx'),
        ),
        migrations.AddIndex(
            model_name='savedmaterial',
            index=models.Index(fields=['user', 'source_group'], name='savedmat_user_src_idx'),
        ),
        migrations.AddField(
            model_name='roominvite',
            name='invitee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_room_invites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roominvite',
            name='inviter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_room_invites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roominvite',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='chat.room'),
        ),
        migrations.AddIndex(
            model_name='roominvite',
            index=models.Index(fields=['invitee', 'status'], name='invite_user_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='roominvite',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('room', 'invitee'), name='unique_pending_invite_per_room_user'),
        ),
    ]
