# Generated by Django 5.2.8 on 2026-05-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_add_message_media_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="media_url",
            field=models.URLField(blank=True),
        ),
    ]
