import 'package:flutter/material.dart';
import 'package:tcs_app/theme/app_colors.dart';
import 'package:tcs_app/widgets/t_text.dart';

class TermsOfServiceScreen extends StatefulWidget {
  const TermsOfServiceScreen({super.key});
  @override
  State<TermsOfServiceScreen> createState() => _TermsOfServiceScreenState();
}

class _TermsOfServiceScreenState extends State<TermsOfServiceScreen> {
  Color get _bg   => AppC.bg;
  Color get _card => AppC.card;
  Color get _text => AppC.text;
  Color get _sub  => AppC.sub;

  @override
  Widget build(BuildContext context) {
    final top = MediaQuery.of(context).padding.top;
    return Scaffold(
      backgroundColor: _bg,
      body: Column(children: [
        Container(
          color: _card,
          padding: EdgeInsets.only(top: top + 12, left: 8, right: 16, bottom: 14),
          child: Row(children: [
            GestureDetector(
              onTap: () => Navigator.pop(context),
              child: Container(
                width: 40, height: 40,
                decoration: BoxDecoration(color: _bg,
                    borderRadius: BorderRadius.circular(12)),
                child: Icon(Icons.arrow_back_rounded, size: 20, color: _text)),
            ),
            const SizedBox(width: 12),
            T('Terms of Service & EULA', style: TextStyle(
                fontFamily: 'Alfa', fontSize: 22, color: _text)),
          ]),
        ),
        Expanded(child: ListView(
          padding: const EdgeInsets.all(20),
          children: [
            T('Effective: 1 January 2026',
                style: TextStyle(fontFamily: 'Momo', fontSize: 12, color: _sub)),
            const SizedBox(height: 16),
            _h('1. Acceptance of Terms'),
            _p('By creating an account or using the TCS mobile '
              'application ("the App"), you agree to be bound by these Terms '
              'of Service. The App is provided by Taylors College Sydney for '
              'the exclusive use of its currently enrolled students, staff, '
              'and authorised guests.'),
            _h('2. Eligibility'),
            _p('You must be a current student or staff member of Taylors '
              'College Sydney to register. Accounts must be created using '
              'your college-issued email address. Sharing your account or '
              'allowing others to access it is prohibited.'),
            _h('3. Acceptable Use'),
            _p('You agree to use the App responsibly. You will not post '
              'content that is unlawful, harassing, defamatory, threatening, '
              'discriminatory, sexually explicit, or that infringes the '
              'intellectual property of others. You will not impersonate '
              'staff, other students, or any third party.'),
            _h('4. Academic Integrity'),
            _p('TCS is a learning community. Posting completed '
              'assessment answers, soliciting contract cheating, or sharing '
              'exam content violates Taylors College Sydney\'s Academic '
              'Integrity Policy and may result in disciplinary action by '
              'the College in addition to removal from the App.'),
            _h('5. User Content'),
            _p('You retain ownership of content you post but grant Taylors '
              'College Sydney a non-exclusive, royalty-free licence to host, '
              'display, and moderate that content within the App for as long '
              'as your account remains active.'),
            _h('6. Moderation'),
            _p('We reserve the right to remove any content and to suspend or '
              'terminate any account that violates these Terms or College '
              'policies, with or without notice.'),
            _h('7. AI Features'),
            _p('The App includes AI-assisted features such as chat helpers '
              'and study tools. Output is generated by automated systems and '
              'may contain errors. You are responsible for verifying any '
              'information before relying on it for assessments or '
              'decisions.'),
            _h('8. Privacy'),
            _p('Your use of the App is also governed by our Privacy Policy, '
              'which forms part of these Terms.'),
            _h('9. Disclaimer'),
            _p('The App is provided "as is" without warranties of any kind. '
              'Taylors College Sydney does not guarantee that the App will '
              'be available without interruption or free of errors.'),
            _h('10. Changes'),
            _p('These Terms may be updated from time to time. Continued use '
              'of the App after changes are posted constitutes your '
              'acceptance of the revised Terms.'),
            _h('11. Contact'),
            _p('Questions about these Terms can be directed to the Taylors '
              'College Sydney IT Helpdesk at helpdesk@taylorscollege.edu.au.'),

            const SizedBox(height: 28),
            _h('End User License Agreement (EULA)'),
            _p('This End User License Agreement ("EULA") governs your use '
              'of the TCS mobile application. By tapping "I agree" on the '
              'sign-in screen, or by otherwise using the App, you accept '
              'the terms set out below in addition to the Terms of Service '
              'above.'),
            _h('A. Licence Grant'),
            _p('Taylors College Sydney (the "Licensor") grants you a '
              'limited, non-transferable, non-exclusive, revocable licence '
              'to install and use the App on any Apple-branded or Android '
              'device that you own or control, solely for your personal, '
              'non-commercial use as a current student, staff member, or '
              'authorised guest of Taylors College Sydney.'),
            _h('B. Restrictions'),
            _p('You may not copy, modify, reverse engineer, decompile, or '
              'disassemble the App, attempt to derive its source code, or '
              'create derivative works of it. You may not redistribute, '
              'sub-licence, lease, lend, or sell the App, or remove any '
              'proprietary notices.'),
            _h('C. Acceptable Conduct (UGC)'),
            _p('There is zero tolerance for objectionable, abusive, '
              'harassing, hateful, sexually explicit, or threatening '
              'content. The App provides in-app tools to report content '
              'and to block users; reports are reviewed and acted upon '
              'within 24 hours, with content removal and account '
              'suspension where appropriate.'),
            _h('D. Data and Privacy'),
            _p('You consent to the collection and use of technical and '
              'related information as described in our Privacy Policy, '
              'gathered periodically to facilitate software updates, '
              'product support, and other services related to the App.'),
            _h('E. No Warranty'),
            _p('The App is provided on an "AS IS" and "AS AVAILABLE" '
              'basis, without warranty of any kind, express or implied. '
              'To the maximum extent permitted by law, the Licensor '
              'disclaims all warranties, including merchantability, '
              'fitness for a particular purpose, accuracy, and '
              'non-infringement.'),
            _h('F. Limitation of Liability'),
            _p('To the maximum extent permitted by law, in no event shall '
              'the Licensor be liable for any incidental, special, '
              'indirect, or consequential damages whatsoever, including '
              'loss of data, lost profits, or business interruption, '
              'arising out of or related to your use of the App.'),
            _h('G. Termination'),
            _p('This licence is effective until terminated. Your rights '
              'under this licence will terminate automatically without '
              'notice if you fail to comply with any of its terms, or if '
              'you cease to be a current student, staff member, or '
              'authorised guest of Taylors College Sydney. Upon '
              'termination, you must cease all use of the App and delete '
              'all copies from your device.'),
            _h('H. Apple-Specific Terms'),
            _p('You acknowledge that this EULA is between you and the '
              'Licensor only, and not with Apple, and that Apple is not '
              'responsible for the App or its content. Apple has no '
              'obligation to provide maintenance or support services for '
              'the App. In the event of any failure of the App to conform '
              'to any applicable warranty, you may notify Apple, and '
              'Apple will refund the purchase price (if any) for the App; '
              'to the maximum extent permitted by law, Apple has no other '
              'warranty obligation with respect to the App. Apple and '
              'Apple\'s subsidiaries are third-party beneficiaries of '
              'this EULA and have the right to enforce it against you.'),
            _h('I. Export Compliance'),
            _p('You represent that you are not located in a country that '
              'is subject to a U.S. Government embargo, and that you are '
              'not on any U.S. Government list of prohibited or '
              'restricted parties. You will comply with all applicable '
              'export laws and regulations.'),
            _h('J. Governing Law'),
            _p('This EULA is governed by the laws of New South Wales, '
              'Australia, without regard to its conflict-of-law '
              'provisions. Disputes will be subject to the exclusive '
              'jurisdiction of the courts of New South Wales.'),

            const SizedBox(height: 40),
          ],
        )),
      ]),
    );
  }

  Widget _h(String t) => Padding(
    padding: const EdgeInsets.only(top: 18, bottom: 6),
    child: Text(t, style: TextStyle(
        fontFamily: 'Arch', fontWeight: FontWeight.bold,
        fontSize: 15, color: _text)),
  );
  Widget _p(String t) => Text(t, style: TextStyle(
      fontFamily: 'Momo', fontSize: 13, color: _sub, height: 1.6));
}