import 'package:flutter/material.dart';
import 'package:tcs_app/services/app_settings.dart';

class TermsOfServiceScreen extends StatefulWidget {
  const TermsOfServiceScreen({super.key});
  @override
  State<TermsOfServiceScreen> createState() => _TermsOfServiceScreenState();
}

class _TermsOfServiceScreenState extends State<TermsOfServiceScreen> {
  final _s = AppSettings();
  bool get _dark => _s.isDark;

  Color get _bg   => _dark ? const Color(0xFF0D0D1A) : const Color(0xFFF2F4F8);
  Color get _card => _dark ? const Color(0xFF161628) : Colors.white;
  Color get _text => _dark ? Colors.white            : const Color(0xFF1A1A2E);
  Color get _sub  => _dark ? Colors.white70          : Colors.grey.shade700;

  @override
  Widget build(BuildContext context) {
    final top = MediaQuery.of(context).padding.top;
    return Scaffold(
      backgroundColor: _bg,
      body: Column(children: [
        Container(
          color: _card,
          padding: EdgeInsets.only(top: top + 12, left: 8, right: 16, bottom: 14),
          child: Row(children: [
            GestureDetector(
              onTap: () => Navigator.pop(context),
              child: Container(
                width: 40, height: 40,
                decoration: BoxDecoration(color: _bg,
                    borderRadius: BorderRadius.circular(12)),
                child: Icon(Icons.arrow_back_rounded, size: 20, color: _text)),
            ),
            const SizedBox(width: 12),
            Text('Terms of Service', style: TextStyle(
                fontFamily: 'Alfa', fontSize: 22, color: _text)),
          ]),
        ),
        Expanded(child: ListView(
          padding: const EdgeInsets.all(20),
          children: [
            Text('Effective: 1 January 2026',
                style: TextStyle(fontFamily: 'Momo', fontSize: 12, color: _sub)),
            const SizedBox(height: 16),
            _h('1. Acceptance of Terms'),
            _p('By creating an account or using the TCS mobile '
              'application ("the App"), you agree to be bound by these Terms '
              'of Service. The App is provided by Taylors College Sydney for '
              'the exclusive use of its currently enrolled students, staff, '
              'and authorised guests.'),
            _h('2. Eligibility'),
            _p('You must be a current student or staff member of Taylors '
              'College Sydney to register. Accounts must be created using '
              'your college-issued email address. Sharing your account or '
              'allowing others to access it is prohibited.'),
            _h('3. Acceptable Use'),
            _p('You agree to use the App responsibly. You will not post '
              'content that is unlawful, harassing, defamatory, threatening, '
              'discriminatory, sexually explicit, or that infringes the '
              'intellectual property of others. You will not impersonate '
              'staff, other students, or any third party.'),
            _h('4. Academic Integrity'),
            _p('TCS is a learning community. Posting completed '
              'assessment answers, soliciting contract cheating, or sharing '
              'exam content violates Taylors College Sydney\'s Academic '
              'Integrity Policy and may result in disciplinary action by '
              'the College in addition to removal from the App.'),
            _h('5. User Content'),
            _p('You retain ownership of content you post but grant Taylors '
              'College Sydney a non-exclusive, royalty-free licence to host, '
              'display, and moderate that content within the App for as long '
              'as your account remains active.'),
            _h('6. Moderation'),
            _p('We reserve the right to remove any content and to suspend or '
              'terminate any account that violates these Terms or College '
              'policies, with or without notice.'),
            _h('7. AI Features'),
            _p('The App includes AI-assisted features such as chat helpers '
              'and study tools. Output is generated by automated systems and '
              'may contain errors. You are responsible for verifying any '
              'information before relying on it for assessments or '
              'decisions.'),
            _h('8. Privacy'),
            _p('Your use of the App is also governed by our Privacy Policy, '
              'which forms part of these Terms.'),
            _h('9. Disclaimer'),
            _p('The App is provided "as is" without warranties of any kind. '
              'Taylors College Sydney does not guarantee that the App will '
              'be available without interruption or free of errors.'),
            _h('10. Changes'),
            _p('These Terms may be updated from time to time. Continued use '
              'of the App after changes are posted constitutes your '
              'acceptance of the revised Terms.'),
            _h('11. Contact'),
            _p('Questions about these Terms can be directed to the Taylors '
              'College Sydney IT Helpdesk at helpdesk@taylorscollege.edu.au.'),
            const SizedBox(height: 40),
          ],
        )),
      ]),
    );
  }

  Widget _h(String t) => Padding(
    padding: const EdgeInsets.only(top: 18, bottom: 6),
    child: Text(t, style: TextStyle(
        fontFamily: 'Arch', fontWeight: FontWeight.bold,
        fontSize: 15, color: _text)),
  );
  Widget _p(String t) => Text(t, style: TextStyle(
      fontFamily: 'Momo', fontSize: 13, color: _sub, height: 1.6));
}