# Generated by Django 4.2.16 on 2026-05-08 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiCompanion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(help_text='Short tagline shown on cards', max_length=200)),
                ('instructions', models.TextField(help_text='Persona instructions: backstory, voice, behaviour rules')),
                ('seed_chat', models.TextField(blank=True, help_text='Optional example exchanges that anchor tone')),
                ('avatar_emoji', models.CharField(default='🤖', max_length=8)),
                ('gradient_start', models.CharField(default='#6A11CB', help_text='Hex like #RRGGBB', max_length=9)),
                ('gradient_end', models.CharField(default='#2575FC', max_length=9)),
                ('category', models.CharField(choices=[('science', 'Science'), ('literature', 'Literature'), ('philosophy', 'Philosophy'), ('history', 'History'), ('tech', 'Tech'), ('study', 'Study'), ('general', 'General')], default='general', max_length=20)),
                ('is_public', models.BooleanField(default=True)),
                ('is_seed', models.BooleanField(default=False, help_text='True for built-in personas (cannot be deleted via API)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_companions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_seed', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('companion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='ai.aicompanion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companion_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=12)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai.conversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageGeneration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('model', models.CharField(choices=[('flux', 'FLUX (high quality)'), ('turbo', 'Turbo (fast)'), ('flux-realism', 'FLUX Realism'), ('flux-anime', 'FLUX Anime')], default='flux', max_length=20)),
                ('width', models.PositiveIntegerField(default=1024)),
                ('height', models.PositiveIntegerField(default=1024)),
                ('seed', models.BigIntegerField()),
                ('image_url', models.URLField(max_length=2000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='succeeded', max_length=12)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_generations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='ai_imagegen_user_id_12d8c9_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', 'companion', '-updated_at'], name='ai_conversa_user_id_a16f8f_idx'),
        ),
        migrations.AddIndex(
            model_name='aicompanion',
            index=models.Index(fields=['category', 'is_public'], name='ai_aicompan_categor_e91a71_idx'),
        ),
    ]
