# Generated by Django 4.2.16 on 2026-05-10 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrecord',
            name='date_of_finishing',
            field=models.DateField(blank=True, null=True),
        ),
    ]
