# Generated by Django 5.2.8 on 2026-05-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_extended_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notif_type",
            field=models.CharField(
                choices=[
                    ("like", "Like"),
                    ("comment", "Comment"),
                    ("follow", "Follow"),
                    ("mention", "Mention"),
                    ("chat_message", "Chat Message"),
                    ("chat_request", "Chat Request"),
                    ("request_accepted", "Request Accepted"),
                    ("request_declined", "Request Declined"),
                    ("group_add", "Added to Group"),
                    ("group_message", "Group Message"),
                    ("group_material", "Group Material"),
                    ("club_event", "Club Event"),
                    ("game_request", "Game Request"),
                    ("event_reminder", "Event Reminder"),
                    ("achievement", "Achievement"),
                    ("system", "System"),
                ],
                max_length=20,
            ),
        ),
    ]
