// lib/main.dart
import 'dart:async' show unawaited;
import 'dart:io' show Platform; // ← FIX: needed for Platform.isIOS check
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:get/get.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:tcs_app/screens/splash_screen.dart';
import 'package:tcs_app/screens/noticeboard_screen.dart';

import 'package:tcs_app/services/auth_service.dart';
import 'package:tcs_app/services/notification_Service.dart';

import 'services/api_service.dart';
import 'services/translation_service.dart';
import 'services/app_localisations.dart';
import 'services/app_settings.dart';
import 'firebase_options.dart'; // generated by `flutterfire configure`

// ─────────────────────────────────────────────────────────────
// PUSH NOTIFICATION INFRASTRUCTURE
// ─────────────────────────────────────────────────────────────

final FlutterLocalNotificationsPlugin localNotifications =
    FlutterLocalNotificationsPlugin();

const AndroidNotificationChannel _channelAll = AndroidNotificationChannel(
  'tcs_all', 'All Notifications',
  description: 'Default channel for TCS',
  importance: Importance.high,
);
const AndroidNotificationChannel _channelAnn = AndroidNotificationChannel(
  'tcs_announcements', 'Announcements',
  description: 'Campus-wide announcements',
  importance: Importance.high,
);
const AndroidNotificationChannel _channelGroup = AndroidNotificationChannel(
  'tcs_group_activity', 'Group Activity',
  description: 'New posts in your groups',
  importance: Importance.defaultImportance,
);

// Top-level (or static) — required for FCM to invoke when app is killed
@pragma('vm:entry-point')
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform);
  // FCM "notification" payloads auto-display via the system tray when the
  // app is in background/killed, so this handler is a no-op for those.
  // Add custom logic here if you ever send data-only payloads.
}

Future<void> _initLocalNotifications() async {
  const androidInit = AndroidInitializationSettings('@mipmap/ic_launcher');
  const iosInit = DarwinInitializationSettings(
    requestAlertPermission: false,
    requestBadgePermission: false,
    requestSoundPermission: false,
  );
  await localNotifications.initialize(
    settings: const InitializationSettings(android: androidInit, iOS: iosInit),
  );
  final android = localNotifications
      .resolvePlatformSpecificImplementation<AndroidFlutterLocalNotificationsPlugin>();
  await android?.createNotificationChannel(_channelAll);
  await android?.createNotificationChannel(_channelAnn);
  await android?.createNotificationChannel(_channelGroup);
}

Future<void> _initFcm() async {
  // Background handler MUST be registered before any other listeners
  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);

  // Foreground messages: FCM does NOT show these automatically — render
  // them ourselves via flutter_local_notifications
  FirebaseMessaging.onMessage.listen((RemoteMessage msg) {
    final n = msg.notification;
    if (n == null) return;
    final ch = _pickChannel(msg);
    localNotifications.show(
      id: msg.hashCode,
      title: n.title,
      body: n.body,
      notificationDetails: NotificationDetails(
        android: AndroidNotificationDetails(
          ch.id, ch.name,
          channelDescription: ch.description,
          importance: ch.importance,
          icon: '@mipmap/ic_launcher',
        ),
        iOS: const DarwinNotificationDetails(),
      ),
    );
  });

  // Re-register the device token with the backend whenever FCM rotates it.
  FirebaseMessaging.instance.onTokenRefresh.listen((token) async {
    try { await ApiService().updateFcmToken(token); } catch (_) {}
  });

  // Deep-link announcement push taps → Noticeboard.
  // • App in background: route immediately (GetMaterialApp is mounted).
  // • App launched from terminated state: stash the id; the splash opens the
  //   board once it has routed to the dashboard (avoids a navigation race).
  FirebaseMessaging.onMessageOpenedApp.listen((msg) => _routeAnnouncement(msg.data));
  final initialMsg = await FirebaseMessaging.instance.getInitialMessage();
  if (initialMsg != null && initialMsg.data['type'] == 'announcement') {
    pendingAnnouncementId = (initialMsg.data['announcement_id'] ?? '').toString();
  }

  await syncFcmTopics(); // honor saved user prefs on cold start
}

/// Routes an FCM data payload to the Noticeboard when it is an announcement.
/// Used for the background-tap (onMessageOpenedApp) path while the app runs.
void _routeAnnouncement(Map<String, dynamic> data) {
  if (data['type'] != 'announcement') return;
  final id = (data['announcement_id'] ?? '').toString();
  Get.to(() => NoticeboardScreen(highlightId: id.isEmpty ? null : id));
}

/// Registers THIS device's FCM token with the backend (POST
/// /users/me/fcm-token/) so the server can push to user.fcm_token.
/// Must run while authenticated. Safe to call repeatedly.
Future<void> registerFcmToken() async {
  final fcm = FirebaseMessaging.instance;
  try {
    await fcm.requestPermission(alert: true, badge: true, sound: true);
    if (Platform.isIOS) {
      // APNs delivers its token asynchronously after registration; poll
      // briefly so getToken() doesn't throw apns-token-not-set on first launch.
      String? apns = await fcm.getAPNSToken();
      for (var i = 0; i < 10 && apns == null; i++) {
        await Future.delayed(const Duration(seconds: 1));
        apns = await fcm.getAPNSToken();
      }
      if (apns == null) {
        debugPrint('[FCM] APNs token not ready yet - onTokenRefresh will register later');
        return;
      }
    }
    final token = await fcm.getToken();
    if (token != null && token.isNotEmpty) {
      await ApiService().updateFcmToken(token);
      debugPrint('[FCM] device token registered with backend');
    }
  } catch (e) {
    debugPrint('[FCM] token registration failed: ' + e.toString());
  }
}

AndroidNotificationChannel _pickChannel(RemoteMessage msg) {
  final type = msg.data['type'];
  if (type == 'announcement')   return _channelAnn;
  if (type == 'group_activity') return _channelGroup;
  return _channelAll;
}

/// Re-subscribe / unsubscribe from FCM topics based on the user's saved
/// preferences. Call this from settings_screen.dart whenever a notification
/// toggle changes — it guarantees the user actually controls delivery.
Future<void> syncFcmTopics() async {
  final s = AppSettings();
  final fcm = FirebaseMessaging.instance;

  // ← FIX: On iOS, subscribeToTopic requires an APNS token. The iOS Simulator
  // never gets one (Apple limitation), and even on real devices it can take a
  // moment after launch. Skip topic sync gracefully if APNS isn't ready.
  if (Platform.isIOS) {
    try {
      final apnsToken = await fcm.getAPNSToken();
      if (apnsToken == null) {
        debugPrint(
            '[FCM] No APNS token yet (likely simulator) — skipping topic sync');
        return;
      }
    } catch (e) {
      debugPrint('[FCM] APNS check failed: $e — skipping topic sync');
      return;
    }
  }

  // ← FIX: Wrap the actual subscribe/unsubscribe calls so a transient
  // network or token issue can't crash the app.
  try {
    if (s.pushEnabled) {
      await fcm.subscribeToTopic('all_users');
      s.announcements
          ? await fcm.subscribeToTopic('announcements')
          : await fcm.unsubscribeFromTopic('announcements');
      s.groupActivity
          ? await fcm.subscribeToTopic('group_activity')
          : await fcm.unsubscribeFromTopic('group_activity');
    } else {
      await fcm.unsubscribeFromTopic('all_users');
      await fcm.unsubscribeFromTopic('announcements');
      await fcm.unsubscribeFromTopic('group_activity');
    }
  } catch (e) {
    debugPrint('[FCM] Topic sync failed: $e');
  }
}

// ─────────────────────────────────────────────────────────────
// APP ENTRY
// ─────────────────────────────────────────────────────────────

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Phones stay portrait-locked; tablets/iPads (shortestSide ≥ 600dp) are freed
  // to rotate so the wide two-pane / NavigationRail layouts can engage.
  //
  // MUST be crash-proof: at cold start on real devices the platform view list
  // can still be empty, so `.views.first` throws StateError. An uncaught throw
  // here aborts main() before runApp() → the app never renders a frame (users
  // just see a dark screen). So we guard it and default to the safe portrait
  // lock; the app itself still switches to wide layouts at runtime via
  // MediaQuery, this only decides whether rotation is *allowed*.
  try {
    final views = WidgetsBinding.instance.platformDispatcher.views;
    final view = views.isNotEmpty ? views.first : null;
    final dpr = view?.devicePixelRatio ?? 0;
    final shortestSide = (view != null && dpr > 0)
        ? (view.physicalSize / dpr).shortestSide
        : 0.0;
    if (shortestSide >= 600) {
      await SystemChrome.setPreferredOrientations(DeviceOrientation.values);
    } else {
      await SystemChrome.setPreferredOrientations([
        DeviceOrientation.portraitUp,
        DeviceOrientation.portraitDown,
      ]);
    }
  } catch (e) {
    debugPrint('[startup] orientation setup skipped: $e');
    await SystemChrome.setPreferredOrientations([
      DeviceOrientation.portraitUp,
      DeviceOrientation.portraitDown,
    ]);
  }
  SystemChrome.setSystemUIOverlayStyle(
    const SystemUiOverlayStyle(
      statusBarColor: Colors.transparent,
      statusBarIconBrightness: Brightness.dark,
    ),
  );

  // Firebase + push BEFORE we touch anything else
  await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform);
  await _initLocalNotifications();

  await ApiService().initialize();
  await AppSettings().load();
  await TranslationService.I.init();

  final hasSession = await AuthService.instance.isLoggedIn;

  // Render the UI IMMEDIATELY. Everything below does network / APNs / FCM work
  // and is NOT needed to draw the first frame. Awaiting any of it before
  // runApp() risks a blank screen on launch: their try/catch blocks guard
  // THROWN errors, not a stalled request, so a slow/unreachable backend (or an
  // FCM topic-subscribe that never returns) would hang main() forever and
  // runApp() would never run. So we defer ALL of it to after the first frame.
  runApp(const TCSApp());

  // Post-frame, fully non-blocking push + session bootstrap.
  unawaited(() async {
    try {
      await _initFcm();
    } catch (e, st) {
      debugPrint('[FCM] init failed (continuing without push): $e\n$st');
    }
    if (hasSession) {
      unawaited(NotificationService.instance.bootstrap());
      unawaited(registerFcmToken());
    }
  }());
}

// ─────────────────────────────────────────────────────────────
// ROOT APP
// ─────────────────────────────────────────────────────────────

class TCSApp extends StatefulWidget {
  const TCSApp({super.key});
  @override
  State<TCSApp> createState() => _TCSAppState();
}

class _TCSAppState extends State<TCSApp> {
  final _settings = AppSettings();

  @override
  void initState() {
    super.initState();
    _settings.addListener(_rebuild);
  }

  @override
  void dispose() {
    _settings.removeListener(_rebuild);
    super.dispose();
  }

  void _rebuild() {
    if (!mounted) return;
    // Rebuild MaterialApp itself (theme/locale swap)...
    setState(() {});
    // ...then force EVERY element in the tree — including pages already pushed
    // on the Navigator and const subtrees — to rebuild. AppC reads
    // AppSettings().isDark directly rather than via an InheritedWidget, so a
    // plain setState only repaints this widget; cached route pages would keep
    // the old theme until popped/re-pushed (the "not all pages change" bug).
    // forceAppUpdate walks the whole element tree and marks each dirty.
    Get.forceAppUpdate();
  }

  // Cold start can't reliably read the device size before runApp() (the view
  // list may be empty), so main() defaults to a safe portrait lock. Once the
  // first frame has a valid MediaQuery we upgrade tablets/iPads to allow
  // rotation. Runs once. Never touches phones (they stay portrait).
  bool _orientationRefined = false;
  void _refineOrientation(BuildContext context) {
    if (_orientationRefined) return;
    final shortest = MediaQuery.maybeOf(context)?.size.shortestSide ?? 0;
    if (shortest <= 0) return; // metrics not ready yet — try again next frame
    _orientationRefined = true;
    if (shortest >= 600) {
      SystemChrome.setPreferredOrientations(DeviceOrientation.values);
    }
  }

  @override
  Widget build(BuildContext context) {
    return AppL10nProvider(
      languageCode: _settings.lang,
      child: GetMaterialApp(
        title: 'Taylors College',
        debugShowCheckedModeBanner: false,
        defaultTransition: Transition.cupertino,
        transitionDuration: const Duration(milliseconds: 350),
        builder: (context, child) {
          _refineOrientation(context);
          return child ?? const SizedBox.shrink();
        },

        themeMode: _settings.themeMode,
        theme:     _lightTheme,
        darkTheme: _darkTheme,

        locale: _settings.locale,
        supportedLocales: const [
          Locale('en'),
          Locale('ms'),
          Locale('zh'),
          Locale('ja'),   // ← replaced ta
          Locale('ko'),   // ← new
          Locale('ar'),
        ],

        localizationsDelegates: const [
          GlobalMaterialLocalizations.delegate,
          GlobalCupertinoLocalizations.delegate,
          GlobalWidgetsLocalizations.delegate,
        ],

        home: const SplashScreen(),
      ),
    );
  }

  // ── Light theme ───────────────────────────────────────────
  // Built ONCE (static final), not per-build. ColorScheme.fromSeed runs the
  // Material-3 tonal-palette algorithm, which is expensive; recomputing both
  // themes on every rebuild is what made the light/dark switch feel sluggish.
  static final ThemeData _lightTheme = ThemeData(
    useMaterial3: true,
    brightness: Brightness.light,
    colorScheme: ColorScheme.fromSeed(
      seedColor: const Color(0xFF8E54E9),
      brightness: Brightness.light,
    ),
    scaffoldBackgroundColor: const Color(0xFFF7F8FA),
    appBarTheme: const AppBarTheme(
      centerTitle: true, elevation: 0, scrolledUnderElevation: 0,
      backgroundColor: Colors.transparent, foregroundColor: Colors.white,
    ),
    cardTheme: CardThemeData(
      elevation: 0, color: Colors.white,
      surfaceTintColor: Colors.transparent,
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
    ),
    elevatedButtonTheme: ElevatedButtonThemeData(
      style: ElevatedButton.styleFrom(
        elevation: 0,
        padding: const EdgeInsets.symmetric(horizontal: 28, vertical: 14),
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(14)),
        textStyle: const TextStyle(fontFamily: 'Arch',
            fontWeight: FontWeight.bold, fontSize: 15),
      ),
    ),
    inputDecorationTheme: InputDecorationTheme(
      filled: true, fillColor: Colors.white,
      contentPadding: const EdgeInsets.symmetric(horizontal: 20, vertical: 16),
      border: OutlineInputBorder(
        borderRadius: BorderRadius.circular(14), borderSide: BorderSide.none),
      enabledBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(14),
        borderSide: BorderSide(color: Colors.grey.shade200)),
      focusedBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(14),
        borderSide: const BorderSide(color: Color(0xFF8E54E9), width: 2)),
    ),
    bottomNavigationBarTheme: const BottomNavigationBarThemeData(
      backgroundColor: Colors.white, elevation: 0,
      selectedItemColor: Color(0xFF8E54E9),
      unselectedItemColor: Color(0xFFB0B0B0),
      selectedLabelStyle: TextStyle(fontFamily: 'Momo',
          fontSize: 11, fontWeight: FontWeight.w600),
      unselectedLabelStyle: TextStyle(fontFamily: 'Momo', fontSize: 11),
      type: BottomNavigationBarType.fixed, showUnselectedLabels: true,
    ),
    fontFamily: 'Momo',
  );

  // ── Dark theme ────────────────────────────────────────────
  static final ThemeData _darkTheme = ThemeData(
    useMaterial3: true,
    brightness: Brightness.dark,
    colorScheme: ColorScheme.fromSeed(
      seedColor: const Color(0xFF8E54E9), brightness: Brightness.dark),
    scaffoldBackgroundColor: const Color(0xFF0F0F14),
    appBarTheme: const AppBarTheme(
      centerTitle: true, elevation: 0, scrolledUnderElevation: 0,
      backgroundColor: Colors.transparent, foregroundColor: Colors.white,
    ),
    cardTheme: CardThemeData(
      elevation: 0, color: const Color(0xFF1A1A24),
      surfaceTintColor: Colors.transparent,
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
    ),
    elevatedButtonTheme: ElevatedButtonThemeData(
      style: ElevatedButton.styleFrom(
        elevation: 0,
        padding: const EdgeInsets.symmetric(horizontal: 28, vertical: 14),
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(14)),
        textStyle: const TextStyle(fontFamily: 'Arch',
            fontWeight: FontWeight.bold, fontSize: 15),
      ),
    ),
    inputDecorationTheme: InputDecorationTheme(
      filled: true, fillColor: const Color(0xFF1A1A24),
      contentPadding: const EdgeInsets.symmetric(horizontal: 20, vertical: 16),
      border: OutlineInputBorder(
        borderRadius: BorderRadius.circular(14), borderSide: BorderSide.none),
      enabledBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(14),
        borderSide: const BorderSide(color: Color(0xFF2A2A38))),
      focusedBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(14),
        borderSide: const BorderSide(color: Color(0xFF6DD5FA), width: 2)),
    ),
    bottomNavigationBarTheme: const BottomNavigationBarThemeData(
      backgroundColor: Color(0xFF1A1A24), elevation: 0,
      selectedItemColor: Color(0xFF6DD5FA),
      unselectedItemColor: Color(0xFF555566),
      selectedLabelStyle: TextStyle(fontFamily: 'Momo',
          fontSize: 11, fontWeight: FontWeight.w600),
      unselectedLabelStyle: TextStyle(fontFamily: 'Momo', fontSize: 11),
      type: BottomNavigationBarType.fixed, showUnselectedLabels: true,
    ),
    fontFamily: 'Momo',
  );
}