# Generated by Django 4.2.16 on 2026-05-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_avatar_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_available_study',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='study_subjects',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
