# Generated by Django 5.2.8 on 2026-05-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_is_available_study_user_study_subjects"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="social_links",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
