# Generated by Django 5.2.8 on 2026-05-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_social_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="staff_type",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
