# Generated by Django 4.2.16 on 2026-05-07 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        ('posts', '0005_add_feelings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('display', models.CharField(max_length=80)),
                ('posts_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'db_table': 'hashtags',
                'ordering': ['-last_used_at'],
            },
        ),
        migrations.RemoveField(
            model_name='post',
            name='feeling',
        ),
        migrations.AddField(
            model_name='post',
            name='club',
            field=models.ForeignKey(blank=True, help_text='If set, scopes the post to a club.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='clubs.club'),
        ),
        migrations.AlterField(
            model_name='feeling',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='post',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='posts.hashtag'),
        ),
    ]
