# Generated by Django 5.2.8 on 2026-05-24 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0003_clubinvite"),
        ("posts", "0006_hashtag_remove_post_feeling_post_club_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="club",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, scopes the post to a club.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="clubs.club",
            ),
        ),
    ]
